package com.lanou.dllo.myfoodpie.datapotting;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lanou.dllo.myfoodpie.datapotting.QueryData;

import com.lanou.dllo.myfoodpie.datapotting.QueryDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig queryDataDaoConfig;

    private final QueryDataDao queryDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        queryDataDaoConfig = daoConfigMap.get(QueryDataDao.class).clone();
        queryDataDaoConfig.initIdentityScope(type);

        queryDataDao = new QueryDataDao(queryDataDaoConfig, this);

        registerDao(QueryData.class, queryDataDao);
    }
    
    public void clear() {
        queryDataDaoConfig.clearIdentityScope();
    }

    public QueryDataDao getQueryDataDao() {
        return queryDataDao;
    }

}
